name: 'Setup Node.js Environment'
description: 'Sets up Node.js and installs dependencies with caching and cleanup'

inputs:
  auth_token:
    description: 'Authentication token'
    required: true
  base_url:
    description: 'Base URL for the React app'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      env:
        AUTH_TOKEN: ${{ inputs.auth_token }}
        REACT_APP_BASE_URL: ${{ inputs.base_url }}
      uses: actions/setup-node@v3
      with:
        node-version: 20.17.0
        cache: 'npm'

    - name: Clean npm cache and node_modules
      run: |
        rm -rf node_modules
        rm -rf ~/.npm
        rm -rf node_modules/.cache/babel-loader
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
