name: CI_CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node
        with:
          auth_token: ${{ secrets.AUTH_TOKEN }}
          base_url: ${{ secrets.REACT_APP_BASE_URL }}

      - name: Build project
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        run: |
          echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> $GITHUB_ENV
          npm run build

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Run Jest Unit Tests
        run: npm test -- --ci --testPathPattern ".*\\.unit\\.test\\.tsx$"

  integration-tests:
    name: Run Integration Tests
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Run Jest Integration Tests
        run: npm test -- --ci --testPathPattern ".*\\.integration\\.test\\.tsx$"
